#!/usr/bin/env bash
#scripy Y U NO

sudo touch /var/run/holbertonscript.pid
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"

function sigterm {
    echo "I hate the kill command"
    sudo rm /var/run/holbertonscript.pid
    exit
}

function sigint {
    echo "Y U no love me?!"
    exit
}

function sigquit {
    sudo rm /var/run/holbertonscript.pid
    exit
}

trap sigterm SIGTERM
trap sigint SIGINT
trap sigquit SIGQUIT

x=1
while [ $x -lt 2 ]
do
	echo "To infinity and beyond indefinitely"
	# sleep 2
done

