#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

x=0
while [ $x -lt 13 ]
do
	echo "Hour: $x"
	y=1
	while [ $y -lt 60 ]
	do
		echo "$y"
		(( y++ ))
	done
	x=$(( x + 1 ))
done
